#!/usr/bin/env python2

#############################################################################
##                                                                         ##
## scapy.py --- Ferramenta Interativa de manipulacao de pacotes            ##
##              veja http://www.secdev.org/projects/scapy/                 ##
##              para maiores informacoes                                   ##
##                                                                         ##
## Copyright (C) Philippe Biondi <phil@secdev.org>                         ##
##                                                                         ##
## Esse programa e um software livre; voce pode redistribui-lo e/ou        ##
## modifica-lo sob os termos da General Public License versao 2 como       ##
## publicado pela Free Software Foundation.                                ##
##                                                                         ##
## Este programa e distribuido na esperanca que possa ser util, mas sem    ##
## SEM NENHUMA GARANTIA; sem nenhuma garantia implicita de COMERCIALIZACAO ##
## ou ADEQUAÇÃO PARA UM PROPOSITO PARTICULAR. Veja a GNU General Public    ##
## License para maiores detalhes.                                          ##
##                                                                         ##
#############################################################################
##                                                                         ##
## Esta é uma versao especial para suporte ao protocolo Multipath TCP      ##
## Veja README para detalhes.                                              ##
##                                                                         ##
#############################################################################


import os
# use versao local (subdiretorio "scapy" no diretorio corrente)
os.putenv("PYTHONPATH","%s:%s" % (os.getcwd(), os.getenv("PYTHONPATH")))

from scapy.main import interact

interact()
